# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: switch_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "SwitchInfo" do
    optional :value, :string, 1
    optional :type, :uint32, 2
    optional :encoded, :bool, 3
    optional :date, :sint32, 4
    optional :unit_price, :float, 5
  end
end

SwitchInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("SwitchInfo").msgclass
