// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spot_locations.proto

package com.ruckuswireless.spot.proto;

public final class SpotLocations {
  private SpotLocations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Locations)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Locations> {

    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    java.util.List<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location> 
        getLocationsList();
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    com.ruckuswireless.spot.proto.SpotLocations.Locations.Location getLocations(int index);
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    int getLocationsCount();
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    java.util.List<? extends com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder> 
        getLocationsOrBuilderList();
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder getLocationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Locations}
   */
  public static final class Locations extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Locations> implements
      // @@protoc_insertion_point(message_implements:Locations)
      LocationsOrBuilder {
    // Use Locations.newBuilder() to construct.
    private Locations(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.ruckuswireless.spot.proto.SpotLocations.Locations, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Locations(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Locations defaultInstance;
    public static Locations getDefaultInstance() {
      return defaultInstance;
    }

    public Locations getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Locations(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                locations_ = new java.util.ArrayList<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location>();
                mutable_bitField0_ |= 0x00000001;
              }
              locations_.add(input.readMessage(com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          locations_ = java.util.Collections.unmodifiableList(locations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ruckuswireless.spot.proto.SpotLocations.Locations.class, com.ruckuswireless.spot.proto.SpotLocations.Locations.Builder.class);
    }

    public static com.google.protobuf.Parser<Locations> PARSER =
        new com.google.protobuf.AbstractParser<Locations>() {
      public Locations parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Locations(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Locations> getParserForType() {
      return PARSER;
    }

    public interface LocationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Locations.Location)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string venue_id = 1;</code>
       *
       * <pre>
       * ID of the Venue
       * </pre>
       */
      boolean hasVenueId();
      /**
       * <code>optional string venue_id = 1;</code>
       *
       * <pre>
       * ID of the Venue
       * </pre>
       */
      java.lang.String getVenueId();
      /**
       * <code>optional string venue_id = 1;</code>
       *
       * <pre>
       * ID of the Venue
       * </pre>
       */
      com.google.protobuf.ByteString
          getVenueIdBytes();

      /**
       * <code>optional string mac = 2;</code>
       *
       * <pre>
       * Detected/Located device MAC address
       * </pre>
       */
      boolean hasMac();
      /**
       * <code>optional string mac = 2;</code>
       *
       * <pre>
       * Detected/Located device MAC address
       * </pre>
       */
      java.lang.String getMac();
      /**
       * <code>optional string mac = 2;</code>
       *
       * <pre>
       * Detected/Located device MAC address
       * </pre>
       */
      com.google.protobuf.ByteString
          getMacBytes();

      /**
       * <code>optional float x = 3;</code>
       *
       * <pre>
       * x-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      boolean hasX();
      /**
       * <code>optional float x = 3;</code>
       *
       * <pre>
       * x-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      float getX();

      /**
       * <code>optional float y = 4;</code>
       *
       * <pre>
       * y-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      boolean hasY();
      /**
       * <code>optional float y = 4;</code>
       *
       * <pre>
       * y-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      float getY();

      /**
       * <code>optional uint32 floor_number = 5;</code>
       *
       * <pre>
       * positive integer of the floor number where the device is detected
       * </pre>
       */
      boolean hasFloorNumber();
      /**
       * <code>optional uint32 floor_number = 5;</code>
       *
       * <pre>
       * positive integer of the floor number where the device is detected
       * </pre>
       */
      int getFloorNumber();

      /**
       * <code>optional uint32 timestamp = 6;</code>
       *
       * <pre>
       * Unix timestamp when the device is detected (even when it is an outlier)
       * </pre>
       */
      boolean hasTimestamp();
      /**
       * <code>optional uint32 timestamp = 6;</code>
       *
       * <pre>
       * Unix timestamp when the device is detected (even when it is an outlier)
       * </pre>
       */
      int getTimestamp();
    }
    /**
     * Protobuf type {@code Locations.Location}
     *
     * <pre>
     * An outlier is defined when x = y = 0
     * </pre>
     */
    public static final class Location extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Locations.Location)
        LocationOrBuilder {
      // Use Location.newBuilder() to construct.
      private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Location defaultInstance;
      public static Location getDefaultInstance() {
        return defaultInstance;
      }

      public Location getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Location(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                venueId_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                mac_ = bs;
                break;
              }
              case 29: {
                bitField0_ |= 0x00000004;
                x_ = input.readFloat();
                break;
              }
              case 37: {
                bitField0_ |= 0x00000008;
                y_ = input.readFloat();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                floorNumber_ = input.readUInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                timestamp_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.class, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder.class);
      }

      public static com.google.protobuf.Parser<Location> PARSER =
          new com.google.protobuf.AbstractParser<Location>() {
        public Location parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Location(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Location> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int VENUE_ID_FIELD_NUMBER = 1;
      private java.lang.Object venueId_;
      /**
       * <code>optional string venue_id = 1;</code>
       *
       * <pre>
       * ID of the Venue
       * </pre>
       */
      public boolean hasVenueId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string venue_id = 1;</code>
       *
       * <pre>
       * ID of the Venue
       * </pre>
       */
      public java.lang.String getVenueId() {
        java.lang.Object ref = venueId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            venueId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string venue_id = 1;</code>
       *
       * <pre>
       * ID of the Venue
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVenueIdBytes() {
        java.lang.Object ref = venueId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          venueId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MAC_FIELD_NUMBER = 2;
      private java.lang.Object mac_;
      /**
       * <code>optional string mac = 2;</code>
       *
       * <pre>
       * Detected/Located device MAC address
       * </pre>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string mac = 2;</code>
       *
       * <pre>
       * Detected/Located device MAC address
       * </pre>
       */
      public java.lang.String getMac() {
        java.lang.Object ref = mac_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mac_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string mac = 2;</code>
       *
       * <pre>
       * Detected/Located device MAC address
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        java.lang.Object ref = mac_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int X_FIELD_NUMBER = 3;
      private float x_;
      /**
       * <code>optional float x = 3;</code>
       *
       * <pre>
       * x-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float x = 3;</code>
       *
       * <pre>
       * x-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      public float getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 4;
      private float y_;
      /**
       * <code>optional float y = 4;</code>
       *
       * <pre>
       * y-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float y = 4;</code>
       *
       * <pre>
       * y-coordinates of the detected device (possible to be 0)
       * </pre>
       */
      public float getY() {
        return y_;
      }

      public static final int FLOOR_NUMBER_FIELD_NUMBER = 5;
      private int floorNumber_;
      /**
       * <code>optional uint32 floor_number = 5;</code>
       *
       * <pre>
       * positive integer of the floor number where the device is detected
       * </pre>
       */
      public boolean hasFloorNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 floor_number = 5;</code>
       *
       * <pre>
       * positive integer of the floor number where the device is detected
       * </pre>
       */
      public int getFloorNumber() {
        return floorNumber_;
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 6;
      private int timestamp_;
      /**
       * <code>optional uint32 timestamp = 6;</code>
       *
       * <pre>
       * Unix timestamp when the device is detected (even when it is an outlier)
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 timestamp = 6;</code>
       *
       * <pre>
       * Unix timestamp when the device is detected (even when it is an outlier)
       * </pre>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      private void initFields() {
        venueId_ = "";
        mac_ = "";
        x_ = 0F;
        y_ = 0F;
        floorNumber_ = 0;
        timestamp_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getVenueIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getMacBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeFloat(3, x_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFloat(4, y_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeUInt32(5, floorNumber_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeUInt32(6, timestamp_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getVenueIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMacBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, x_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, y_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(5, floorNumber_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(6, timestamp_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.ruckuswireless.spot.proto.SpotLocations.Locations.Location)) {
          return super.equals(obj);
        }
        com.ruckuswireless.spot.proto.SpotLocations.Locations.Location other = (com.ruckuswireless.spot.proto.SpotLocations.Locations.Location) obj;

        boolean result = true;
        result = result && (hasVenueId() == other.hasVenueId());
        if (hasVenueId()) {
          result = result && getVenueId()
              .equals(other.getVenueId());
        }
        result = result && (hasMac() == other.hasMac());
        if (hasMac()) {
          result = result && getMac()
              .equals(other.getMac());
        }
        result = result && (hasX() == other.hasX());
        if (hasX()) {
          result = result && (
              java.lang.Float.floatToIntBits(getX())
              == java.lang.Float.floatToIntBits(
                  other.getX()));
        }
        result = result && (hasY() == other.hasY());
        if (hasY()) {
          result = result && (
              java.lang.Float.floatToIntBits(getY())
              == java.lang.Float.floatToIntBits(
                  other.getY()));
        }
        result = result && (hasFloorNumber() == other.hasFloorNumber());
        if (hasFloorNumber()) {
          result = result && (getFloorNumber()
              == other.getFloorNumber());
        }
        result = result && (hasTimestamp() == other.hasTimestamp());
        if (hasTimestamp()) {
          result = result && (getTimestamp()
              == other.getTimestamp());
        }
        result = result &&
            getUnknownFields().equals(other.getUnknownFields());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasVenueId()) {
          hash = (37 * hash) + VENUE_ID_FIELD_NUMBER;
          hash = (53 * hash) + getVenueId().hashCode();
        }
        if (hasMac()) {
          hash = (37 * hash) + MAC_FIELD_NUMBER;
          hash = (53 * hash) + getMac().hashCode();
        }
        if (hasX()) {
          hash = (37 * hash) + X_FIELD_NUMBER;
          hash = (53 * hash) + java.lang.Float.floatToIntBits(
              getX());
        }
        if (hasY()) {
          hash = (37 * hash) + Y_FIELD_NUMBER;
          hash = (53 * hash) + java.lang.Float.floatToIntBits(
              getY());
        }
        if (hasFloorNumber()) {
          hash = (37 * hash) + FLOOR_NUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getFloorNumber();
        }
        if (hasTimestamp()) {
          hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
          hash = (53 * hash) + getTimestamp();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.ruckuswireless.spot.proto.SpotLocations.Locations.Location prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Locations.Location}
       *
       * <pre>
       * An outlier is defined when x = y = 0
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Locations.Location)
          com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_Location_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_Location_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.class, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder.class);
        }

        // Construct using com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          venueId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          mac_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          x_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000004);
          y_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000008);
          floorNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_Location_descriptor;
        }

        public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location getDefaultInstanceForType() {
          return com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.getDefaultInstance();
        }

        public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location build() {
          com.ruckuswireless.spot.proto.SpotLocations.Locations.Location result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location buildPartial() {
          com.ruckuswireless.spot.proto.SpotLocations.Locations.Location result = new com.ruckuswireless.spot.proto.SpotLocations.Locations.Location(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.venueId_ = venueId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.mac_ = mac_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.y_ = y_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.floorNumber_ = floorNumber_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.timestamp_ = timestamp_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.ruckuswireless.spot.proto.SpotLocations.Locations.Location) {
            return mergeFrom((com.ruckuswireless.spot.proto.SpotLocations.Locations.Location)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.ruckuswireless.spot.proto.SpotLocations.Locations.Location other) {
          if (other == com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.getDefaultInstance()) return this;
          if (other.hasVenueId()) {
            bitField0_ |= 0x00000001;
            venueId_ = other.venueId_;
            onChanged();
          }
          if (other.hasMac()) {
            bitField0_ |= 0x00000002;
            mac_ = other.mac_;
            onChanged();
          }
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          if (other.hasFloorNumber()) {
            setFloorNumber(other.getFloorNumber());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.ruckuswireless.spot.proto.SpotLocations.Locations.Location parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.ruckuswireless.spot.proto.SpotLocations.Locations.Location) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object venueId_ = "";
        /**
         * <code>optional string venue_id = 1;</code>
         *
         * <pre>
         * ID of the Venue
         * </pre>
         */
        public boolean hasVenueId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string venue_id = 1;</code>
         *
         * <pre>
         * ID of the Venue
         * </pre>
         */
        public java.lang.String getVenueId() {
          java.lang.Object ref = venueId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              venueId_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string venue_id = 1;</code>
         *
         * <pre>
         * ID of the Venue
         * </pre>
         */
        public com.google.protobuf.ByteString
            getVenueIdBytes() {
          java.lang.Object ref = venueId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            venueId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string venue_id = 1;</code>
         *
         * <pre>
         * ID of the Venue
         * </pre>
         */
        public Builder setVenueId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          venueId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string venue_id = 1;</code>
         *
         * <pre>
         * ID of the Venue
         * </pre>
         */
        public Builder clearVenueId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          venueId_ = getDefaultInstance().getVenueId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string venue_id = 1;</code>
         *
         * <pre>
         * ID of the Venue
         * </pre>
         */
        public Builder setVenueIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          venueId_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object mac_ = "";
        /**
         * <code>optional string mac = 2;</code>
         *
         * <pre>
         * Detected/Located device MAC address
         * </pre>
         */
        public boolean hasMac() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string mac = 2;</code>
         *
         * <pre>
         * Detected/Located device MAC address
         * </pre>
         */
        public java.lang.String getMac() {
          java.lang.Object ref = mac_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              mac_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string mac = 2;</code>
         *
         * <pre>
         * Detected/Located device MAC address
         * </pre>
         */
        public com.google.protobuf.ByteString
            getMacBytes() {
          java.lang.Object ref = mac_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            mac_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string mac = 2;</code>
         *
         * <pre>
         * Detected/Located device MAC address
         * </pre>
         */
        public Builder setMac(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          mac_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string mac = 2;</code>
         *
         * <pre>
         * Detected/Located device MAC address
         * </pre>
         */
        public Builder clearMac() {
          bitField0_ = (bitField0_ & ~0x00000002);
          mac_ = getDefaultInstance().getMac();
          onChanged();
          return this;
        }
        /**
         * <code>optional string mac = 2;</code>
         *
         * <pre>
         * Detected/Located device MAC address
         * </pre>
         */
        public Builder setMacBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          mac_ = value;
          onChanged();
          return this;
        }

        private float x_ ;
        /**
         * <code>optional float x = 3;</code>
         *
         * <pre>
         * x-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional float x = 3;</code>
         *
         * <pre>
         * x-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public float getX() {
          return x_;
        }
        /**
         * <code>optional float x = 3;</code>
         *
         * <pre>
         * x-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public Builder setX(float value) {
          bitField0_ |= 0x00000004;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float x = 3;</code>
         *
         * <pre>
         * x-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000004);
          x_ = 0F;
          onChanged();
          return this;
        }

        private float y_ ;
        /**
         * <code>optional float y = 4;</code>
         *
         * <pre>
         * y-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional float y = 4;</code>
         *
         * <pre>
         * y-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public float getY() {
          return y_;
        }
        /**
         * <code>optional float y = 4;</code>
         *
         * <pre>
         * y-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public Builder setY(float value) {
          bitField0_ |= 0x00000008;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float y = 4;</code>
         *
         * <pre>
         * y-coordinates of the detected device (possible to be 0)
         * </pre>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000008);
          y_ = 0F;
          onChanged();
          return this;
        }

        private int floorNumber_ ;
        /**
         * <code>optional uint32 floor_number = 5;</code>
         *
         * <pre>
         * positive integer of the floor number where the device is detected
         * </pre>
         */
        public boolean hasFloorNumber() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional uint32 floor_number = 5;</code>
         *
         * <pre>
         * positive integer of the floor number where the device is detected
         * </pre>
         */
        public int getFloorNumber() {
          return floorNumber_;
        }
        /**
         * <code>optional uint32 floor_number = 5;</code>
         *
         * <pre>
         * positive integer of the floor number where the device is detected
         * </pre>
         */
        public Builder setFloorNumber(int value) {
          bitField0_ |= 0x00000010;
          floorNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 floor_number = 5;</code>
         *
         * <pre>
         * positive integer of the floor number where the device is detected
         * </pre>
         */
        public Builder clearFloorNumber() {
          bitField0_ = (bitField0_ & ~0x00000010);
          floorNumber_ = 0;
          onChanged();
          return this;
        }

        private int timestamp_ ;
        /**
         * <code>optional uint32 timestamp = 6;</code>
         *
         * <pre>
         * Unix timestamp when the device is detected (even when it is an outlier)
         * </pre>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional uint32 timestamp = 6;</code>
         *
         * <pre>
         * Unix timestamp when the device is detected (even when it is an outlier)
         * </pre>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>optional uint32 timestamp = 6;</code>
         *
         * <pre>
         * Unix timestamp when the device is detected (even when it is an outlier)
         * </pre>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000020;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 timestamp = 6;</code>
         *
         * <pre>
         * Unix timestamp when the device is detected (even when it is an outlier)
         * </pre>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000020);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Locations.Location)
      }

      static {
        defaultInstance = new Location(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Locations.Location)
    }

    public static final int LOCATIONS_FIELD_NUMBER = 1;
    private java.util.List<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location> locations_;
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    public java.util.List<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location> getLocationsList() {
      return locations_;
    }
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    public java.util.List<? extends com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder> 
        getLocationsOrBuilderList() {
      return locations_;
    }
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    public int getLocationsCount() {
      return locations_.size();
    }
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location getLocations(int index) {
      return locations_.get(index);
    }
    /**
     * <code>repeated .Locations.Location locations = 1;</code>
     */
    public com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder getLocationsOrBuilder(
        int index) {
      return locations_.get(index);
    }

    private void initFields() {
      locations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.ruckuswireless.spot.proto.SpotLocations.Locations>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      for (int i = 0; i < locations_.size(); i++) {
        output.writeMessage(1, locations_.get(i));
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < locations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, locations_.get(i));
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ruckuswireless.spot.proto.SpotLocations.Locations)) {
        return super.equals(obj);
      }
      com.ruckuswireless.spot.proto.SpotLocations.Locations other = (com.ruckuswireless.spot.proto.SpotLocations.Locations) obj;

      boolean result = true;
      result = result && getLocationsList()
          .equals(other.getLocationsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getLocationsCount() > 0) {
        hash = (37 * hash) + LOCATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getLocationsList().hashCode();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ruckuswireless.spot.proto.SpotLocations.Locations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ruckuswireless.spot.proto.SpotLocations.Locations prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Locations}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.ruckuswireless.spot.proto.SpotLocations.Locations, Builder> implements
        // @@protoc_insertion_point(builder_implements:Locations)
        com.ruckuswireless.spot.proto.SpotLocations.LocationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ruckuswireless.spot.proto.SpotLocations.Locations.class, com.ruckuswireless.spot.proto.SpotLocations.Locations.Builder.class);
      }

      // Construct using com.ruckuswireless.spot.proto.SpotLocations.Locations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ruckuswireless.spot.proto.SpotLocations.internal_static_Locations_descriptor;
      }

      public com.ruckuswireless.spot.proto.SpotLocations.Locations getDefaultInstanceForType() {
        return com.ruckuswireless.spot.proto.SpotLocations.Locations.getDefaultInstance();
      }

      public com.ruckuswireless.spot.proto.SpotLocations.Locations build() {
        com.ruckuswireless.spot.proto.SpotLocations.Locations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ruckuswireless.spot.proto.SpotLocations.Locations buildPartial() {
        com.ruckuswireless.spot.proto.SpotLocations.Locations result = new com.ruckuswireless.spot.proto.SpotLocations.Locations(this);
        int from_bitField0_ = bitField0_;
        if (locationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            locations_ = java.util.Collections.unmodifiableList(locations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.locations_ = locations_;
        } else {
          result.locations_ = locationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ruckuswireless.spot.proto.SpotLocations.Locations) {
          return mergeFrom((com.ruckuswireless.spot.proto.SpotLocations.Locations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ruckuswireless.spot.proto.SpotLocations.Locations other) {
        if (other == com.ruckuswireless.spot.proto.SpotLocations.Locations.getDefaultInstance()) return this;
        if (locationsBuilder_ == null) {
          if (!other.locations_.isEmpty()) {
            if (locations_.isEmpty()) {
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLocationsIsMutable();
              locations_.addAll(other.locations_);
            }
            onChanged();
          }
        } else {
          if (!other.locations_.isEmpty()) {
            if (locationsBuilder_.isEmpty()) {
              locationsBuilder_.dispose();
              locationsBuilder_ = null;
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              locationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLocationsFieldBuilder() : null;
            } else {
              locationsBuilder_.addAllMessages(other.locations_);
            }
          }
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ruckuswireless.spot.proto.SpotLocations.Locations parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ruckuswireless.spot.proto.SpotLocations.Locations) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location> locations_ =
        java.util.Collections.emptyList();
      private void ensureLocationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          locations_ = new java.util.ArrayList<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location>(locations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ruckuswireless.spot.proto.SpotLocations.Locations.Location, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder, com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder> locationsBuilder_;

      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public java.util.List<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location> getLocationsList() {
        if (locationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(locations_);
        } else {
          return locationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public int getLocationsCount() {
        if (locationsBuilder_ == null) {
          return locations_.size();
        } else {
          return locationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location getLocations(int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);
        } else {
          return locationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder setLocations(
          int index, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.set(index, value);
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder setLocations(
          int index, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder addLocations(com.ruckuswireless.spot.proto.SpotLocations.Locations.Location value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder addLocations(
          int index, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(index, value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder addLocations(
          com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder addLocations(
          int index, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder addAllLocations(
          java.lang.Iterable<? extends com.ruckuswireless.spot.proto.SpotLocations.Locations.Location> values) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, locations_);
          onChanged();
        } else {
          locationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder clearLocations() {
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public Builder removeLocations(int index) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.remove(index);
          onChanged();
        } else {
          locationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder getLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder getLocationsOrBuilder(
          int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);  } else {
          return locationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public java.util.List<? extends com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder> 
           getLocationsOrBuilderList() {
        if (locationsBuilder_ != null) {
          return locationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(locations_);
        }
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder addLocationsBuilder() {
        return getLocationsFieldBuilder().addBuilder(
            com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.getDefaultInstance());
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder addLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().addBuilder(
            index, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.getDefaultInstance());
      }
      /**
       * <code>repeated .Locations.Location locations = 1;</code>
       */
      public java.util.List<com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder> 
           getLocationsBuilderList() {
        return getLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ruckuswireless.spot.proto.SpotLocations.Locations.Location, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder, com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder> 
          getLocationsFieldBuilder() {
        if (locationsBuilder_ == null) {
          locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ruckuswireless.spot.proto.SpotLocations.Locations.Location, com.ruckuswireless.spot.proto.SpotLocations.Locations.Location.Builder, com.ruckuswireless.spot.proto.SpotLocations.Locations.LocationOrBuilder>(
                  locations_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          locations_ = null;
        }
        return locationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Locations)
    }

    static {
      defaultInstance = new Locations(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Locations)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Locations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Locations_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Locations_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Locations_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024spot_locations.proto\"\250\001\n\tLocations\022&\n\t" +
      "locations\030\001 \003(\0132\023.Locations.Location\032h\n\010" +
      "Location\022\020\n\010venue_id\030\001 \001(\t\022\013\n\003mac\030\002 \001(\t\022" +
      "\t\n\001x\030\003 \001(\002\022\t\n\001y\030\004 \001(\002\022\024\n\014floor_number\030\005 " +
      "\001(\r\022\021\n\ttimestamp\030\006 \001(\r*\t\010\351\007\020\200\200\200\200\002B1\n\035com" +
      ".ruckuswireless.spot.protoB\rSpotLocation" +
      "s\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Locations_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Locations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Locations_descriptor,
        new java.lang.String[] { "Locations", });
    internal_static_Locations_Location_descriptor =
      internal_static_Locations_descriptor.getNestedTypes().get(0);
    internal_static_Locations_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Locations_Location_descriptor,
        new java.lang.String[] { "VenueId", "Mac", "X", "Y", "FloorNumber", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
